swarmcity/boardwalk-ts

package-lock.json, package.json, src/app.tsx, src/config/production.ts, src/config/testnet.ts, src/pages/account.tsx, src/pages/user-wallet/wallet.tsx
Quite a few things have changed in the API:
- From 0.5 to 0.6: https://wagmi.sh/docs/migration-guide#06x-breaking-changes
- From 0.4 to 0.5: https://wagmi.sh/docs/migration-guide#05x-breaking-changes
=> chore: upgrade wagmi to 0.6.0

package-lock.json, package.json
Nothing very important, mostly so we stay up to date as a few things have changed in this new release.
=> chore: upgrade vite to v3

src/pages/marketplaces/services/marketplace.ts
This hook fetches all the selected contract configuration properties (https://github.com/swarmcity/boardwalk-contracts/blob/cde1ccb9ec73997f6032cda325876cbdd1fbe495/src/Marketplace.sol#L41-L47) in one single request whenever possible. The types also reflect which properties will be available, ensuring TypeScript safety.
Usage:
```tsx
const { name, fee, token } = useMarketplaceConfig(address, [
'name',
'fee',
'token'
])
```
I guess this can be used instead of `useMarketplaceName`, which should get deprecated at some point.
=> feat: implement `useMarketplaceConfig`

.github/workflows/pages.yaml
Related: https://github.com/swarmcity/ui-library/pull/40
=> ci: upload build to GitHub Pages

src/pages/marketplaces/services/marketplace-item.tsx, src/pages/marketplaces/services/marketplace-items.tsx
Use `useWakuStoreQuery` instead of duplicating `waku.store.queryHistory` calls. The former also comes with various improvements like race condition fixes and error states.
=> refactor: `useItemReplies`

src/pages/marketplaces/list.tsx, src/pages/marketplaces/services/marketplace-list.tsx
=> feat: add completed deals count

src/pages/marketplaces/services/marketplace-items.tsx, src/services/item.ts
~~EDIT: this does not seem to fix the problem, there must be something more.~~
EDIT2: ok it fixed the problem
=> fix: wait properly for approve token transaction

.github/workflows/pages.yaml, .github/workflows/preview.yaml, .github/workflows/test.yaml
=> ci: update to NodeJS 18

src/pages/marketplaces/item.tsx, src/ui/components/in-deal.tsx
=> feat: provider sees confirmation that they are in a deal

src/pages/marketplaces/item.tsx, src/pages/marketplaces/marketplace.tsx, src/pages/user/index.tsx, src/ui/components/reply.tsx, src/ui/components/request.tsx
=> feat: on user click display reputation page

src/pages/marketplaces/item.tsx, src/pages/marketplaces/marketplace.tsx, src/pages/user/index.tsx, src/services/profile.ts
=> feat: show username and avatar everywhere in the app

src/pages/marketplaces/item.tsx, src/pages/marketplaces/list-item.tsx, src/pages/marketplaces/services/marketplace-item.tsx, src/pages/marketplaces/services/marketplace-items.tsx, src/services/item.ts, src/services/select-provider.ts
=> fix: correctly indicate action is being performed after wallet is unlocked

src/pages/marketplaces/item.tsx, src/pages/marketplaces/marketplace.tsx, src/ui/components/request.tsx
=> fix: show provider avatar in request listing only if there is a provider

src/pages/marketplaces/item.tsx, src/pages/marketplaces/list-item.tsx, src/pages/marketplaces/marketplace.tsx, src/pages/marketplaces/services/marketplace.ts, src/ui/components/payment-detail.tsx, src/ui/components/request.tsx
Partially addresses #32 but I will tackle it separately as it means much broader change.
=> feat: show marketplace token everywhere in the app

src/pages/marketplaces/item.tsx, src/pages/marketplaces/marketplace.tsx, src/pages/marketplaces/services/marketplace.ts, src/pages/marketplaces/user-account.tsx
=> feat: show correct token balance in each marketplace

src/lib/cache.ts, src/pages/marketplaces/services/marketplace.ts
This is a quite simple hook, probably not versatile enough, but should do for quite a few cases.
=> feat: cache marketplace and token names

src/pages/marketplaces/item.tsx, src/ui/components/payment-detail.tsx
=> fix: anonymous user does not see completed deal details

src/pages/marketplaces/marketplace.tsx, src/ui/components/reply.tsx, src/ui/components/request.tsx
=> fix: reputation token name and show reputation in request and replies

src/pages/marketplaces/services/marketplace-items.tsx
I've confirmed that it correctly updates the `items` from `useMarketplaceItems`, but it doesn't seem to update the UI. Maybe @vojtechsimetka has more insight regarding that?
This also fixes side effects when `useMarketplaceItems` was called multiple times. This issue might not have manifested itself in the past as `wakuItems.lastUpdate` and `chainItems.lastUpdate` didn't update without doing a whole refresh (e.g. different marketplace).
=> feat: automatically update item status

src/containers/marketplace-reputation.tsx
=> fix: seeker and provider reputation swapped

.postcssrc.json, package-lock.json, package.json, src/components/modals/password/password.module.css, src/components/modals/password/password.tsx
=> fix: styles on the password modal

src/pages/marketplaces/item.tsx, src/pages/marketplaces/list-item.tsx, src/pages/marketplaces/marketplace.tsx, src/pages/marketplaces/user-account.tsx, src/pages/user-wallet/wallet.tsx, src/ui/components/marketplace-item.tsx, src/ui/components/marketplace-reputation.tsx, src/ui/components/payment-detail.tsx, src/ui/components/reply.tsx, src/ui/components/request.tsx, src/ui/utils.ts
=> fix: decimals in the app should now be limited to maximum of 2

src/pages/marketplaces/item.tsx
resolves https://github.com/swarmcity/boardwalk-ts/issues/114
=> fix: unselect button to be blue

src/pages/marketplaces/item.tsx
resolves #138 
Should be thoroughly tested before merged.
=> fix: remove the force page reload

src/pages/marketplaces/item.tsx
=> fix: correctly show select provider button and fix the interaction

src/pages/marketplaces/item.tsx
=> fix: my username in request is not clickable and the font color is black

package-lock.json, package.json, src/pages/marketplaces/item.tsx, src/pages/user-wallet/wallet.tsx
=> fix: margins on confirm modal and loading screen

src/pages/user-wallet/private.tsx
=> fix: replace your public key with your address

src/pages/marketplaces/item.tsx, src/ui/components/in-deal.tsx
=> fix: margins arount the payout button

src/pages/marketplaces/marketplace.tsx, src/ui/components/request.tsx
=> feat: implement all visible states an item can have

src/pages/marketplaces/item.tsx, src/ui/components/reply.tsx
=> fix: choose reply icon button shadow being partially hidden

src/pages/marketplaces/marketplace.tsx
=> fix: alignment of fetching marketplace data

package-lock.json, package.json, src/pages/marketplaces/item.tsx
=> feat: add unselect user flow ui

src/ui/components/request.tsx
=> feat: add in conflict state to the request item

src/containers/in-conflict.tsx, src/containers/resolve-conflict.tsx, src/css/style.css, src/pages/marketplaces/item.tsx
https://user-images.githubusercontent.com/7974813/198694051-a19aa19b-705f-4ea3-abae-a30cf80efe41.mov
=> feat: resolve conflict flow

src/pages/marketplaces/item.tsx, src/ui/components/conflict-resolution-detail.tsx
=> feat: implement resolved conflict summary screen

src/pages/marketplaces/item.tsx
=> fix: add onclick event action to selected reply user click

src/services/profile-picture.tsx, src/services/profile.tsx
Two quite important things:
1) I was refreshing the profile every 86.4 seconds instead of every day... Not great.
2) The profile picture was not being synced.
To force a refresh on a local profile, please run:
```js
const profile = JSON.parse(localStorage.getItem('store_profile'))
delete profile.lastUpdate
localStorage.setItem('store_profile', JSON.stringify(profile))
```
=> fix: profile sync
